using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("3.1.0.221")]
[assembly: AssemblyFileVersionAttribute("3.1.0.221")]
[assembly: AssemblyProductAttribute("extdirect4dotnet")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyInformationalVersionAttribute("3.1.0.221")]

